package andersenLab.tests;// Generated by Selenium IDE

import helpers.ContactPage;
import helpers.LoginPage;
import io.qameta.allure.junit4.DisplayName;
import org.junit.Test;
import org.openqa.selenium.WebDriver;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;

import static org.junit.Assert.assertEquals;

public class ContactFaceCreationTest extends TestBase {
    private WebDriver driver;
    private Properties properties;
    private LoginPage loginPage;
    private ContactPage contactPageNew;

    @Test
    @DisplayName("Contact face creation test")
    public void contactFaceCreation() throws IOException {
        driver = super.driver;
        properties = new Properties();
        properties.load(new FileReader(new File("src/main/resources/local.properties")));
        loginPage = new LoginPage(driver);
        contactPageNew = loginPage.setUsername(properties.getProperty("web.username"))
                .setPassword(properties.getProperty("web.password"))
                .clickSignInButton()
                .selectContactFace()
                .creationOfContactFace()
                .saveContactFace();
        assertEquals(true, contactPageNew.isTitleDisplayed());
    }
}
