package andersenLab.tests;// Generated by Selenium IDE

import andersenLab.helpers.*;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;
import java.util.concurrent.TimeUnit;

import static org.junit.Assert.assertEquals;

public class ProjectCreationTest extends TestBase {
    private WebDriver driver;
    private WebDriverWait wait;
    private HomePage homePage;
    private Properties properties;
    private ContactPage contactPage;
    private ContactPage contactPageNew;
    private ContactFaceCreationPage contactFaceCreationPage;
    private ProjectPage projectPage;
    private ProjectPage projectPageNew;
    private ProjectCreationPage projectCreationPage;

    @Test
    public void projectCreation() throws IOException {
        driver = super.driver;
        properties = new Properties();
        properties.load(new FileReader(new File("src/main/resources/local.properties")));
        LoginPage loginPage = new LoginPage(driver);
        loginPage.setUsername(properties.getProperty("web.username"));
        loginPage.setPassword(properties.getProperty("web.password"));
        homePage = loginPage.clickSignInButton();
        String expectedTitle = "Все Мои проекты";
        projectPage = homePage.selectProject();
        projectPage.createProject();
        assertEquals(expectedTitle,projectPage.getText());
    }

}
