package andersenLab.tests;// Generated by Selenium IDE

import helpers.*;
import io.qameta.allure.junit4.DisplayName;
import org.junit.Test;
import org.openqa.selenium.WebDriver;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;

import static org.junit.Assert.assertEquals;

public class ProjectCreationTest extends TestBase {
    private WebDriver driver;
    private Properties properties;
    private LoginPage loginPage;
    private ProjectPage projectPage;

    @Test
    @DisplayName("Project creation test")
    public void projectCreation() throws IOException {
        driver = super.driver;
        properties = new Properties();
        properties.load(new FileReader(new File("src/main/resources/local.properties")));
        String expectedTitle = "Все Проекты";
        loginPage = new LoginPage(driver);
        projectPage = loginPage.setUsername(properties.getProperty("web.username"))
                .setPassword(properties.getProperty("web.password"))
                .clickSignInButton()
                .selectProject()
                .createProject()
                .createProjectInfo();
        assertEquals(expectedTitle, projectPage.getText());
    }

}
