package andersenLab;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;

import static org.junit.Assert.assertEquals;

public class ProjectCreationTest {
    private WebDriver driver;
    private WebDriverWait wait;

    private void waitAndClick(WebDriver driver, By selector) {
        wait.until(ExpectedConditions.invisibilityOfElementLocated(By.className(("loader-overlay"))));
        wait.until(ExpectedConditions.elementToBeClickable(selector));
        wait.until(ExpectedConditions.invisibilityOfElementLocated(By.className(("loader-overlay"))));
        driver.findElement(selector).click();
    }

    @Before
    public void setUp() {
        String chromeDriverPath = "\\src\\main\\resources\\chromedriver.exe";
        String path = System.getProperty("user.dir");
        System.setProperty("webdriver.chrome.driver", path + chromeDriverPath);
        driver = new ChromeDriver();
        wait = new WebDriverWait(driver, 15);
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void projectCreation() {
        String expectedTitle = "Все Проекты";
        driver.get("https://crm.geekbrains.space/user/login");
        driver.manage().window().setSize(new Dimension(1050, 840));
        waitAndClick(driver, By.id("prependedInput"));
//login to App
        driver.findElement(By.id("prependedInput")).sendKeys("Applanatest1");
        driver.findElement(By.id("prependedInput2")).click();
        driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
        driver.findElement(By.id("_submit")).click();
//Open Project Menu
        WebElement element = driver.findElement(By.xpath("//span[contains(.,'Проекты')]"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
        driver.findElement(By.xpath("//span[contains(.,'Мои проекты')]")).click();
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//Create new Project
        waitAndClick(driver, By.linkText("Создать проект"));
        waitAndClick(driver, By.cssSelector("[data-name=\"field__name\"]"));
        CharSequence uniqueName = "aData_" + System.currentTimeMillis();
        driver.findElement(By.cssSelector("[data-name=\"field__name\"]")).sendKeys(uniqueName);
        driver.findElement(By.cssSelector(".company-container .select2-chosen")).click();
        driver.findElement(By.xpath("//div[contains(@class, 'select2-result-label') and text()='1234']")).click();
        driver.findElement(By.cssSelector("[data-name=\"field__business-unit\"]")).click();
        WebElement dropdownBusinessUnit = driver.findElement(By.cssSelector("[data-name=\"field__business-unit\"]"));
        dropdownBusinessUnit.findElement(By.xpath("//option[. = 'Research & Development']")).click();
        driver.findElement(By.cssSelector("[data-name=\"field__curator\"]")).click();
        WebElement dropdownCurator = driver.findElement(By.cssSelector("[data-name=\"field__curator\"]"));
        dropdownCurator.findElement(By.xpath("//option[. = 'Ким Юрий']")).click();
        driver.findElement(By.cssSelector("[data-name=\"field__rp\"]")).click();
        WebElement dropdownRp = driver.findElement(By.cssSelector("[data-name=\"field__rp\"]"));
        dropdownRp.findElement(By.xpath("//option[. = 'Ермакова Анастасия']")).click();
        driver.findElement(By.cssSelector("[data-name=\"field__administrator\"]")).click();
        WebElement dropdownAdmin = driver.findElement(By.cssSelector("[data-name=\"field__administrator\"]"));
        dropdownAdmin.findElement(By.xpath("//option[. = 'Исаева Анастасия']")).click();
        driver.findElement(By.cssSelector("[data-name=\"field__manager\"]")).click();
        WebElement dropdownManager = driver.findElement(By.cssSelector("[data-name=\"field__manager\"]"));
        dropdownManager.findElement(By.xpath("//option[. = 'Воденеева Алла']")).click();
        driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
        wait.until(ExpectedConditions.visibilityOfAllElementsLocatedBy(By.cssSelector(".oro-subtitle")));
// assert page valid
        String actualTitle = driver.findElement(By.cssSelector(".oro-subtitle")).getText();
        assertEquals(expectedTitle, actualTitle);
    }

}
